# 服务端口
server:
  port: 8082
#开发环境数据库
spring:
  # mysql数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: dreamtech1012
    url: jdbc:mysql://39.100.59.197:3306/labequip?serverTimezone=GMT%2B8
    username: root
